alertmanager:
  ingress:
    enabled: true
    ingressClassName: kong
    hosts:
      - "alermanager.local"
    paths:
      - /
    pathType: Prefix
grafana:
    ingress:
        enabled: true
        ingressClassName: kong
        hosts:
        - "grafana.local"
        path: /
