alertmanager:
  ingress:
    enabled: true
    ingressClassName: kong
    hosts:
      - alertmanager.loan-calculator.local
    paths:
      - /
    pathType: Prefix
grafana:
    ingress:
        enabled: true
        ingressClassName: kong
        hosts:
        - grafana.loan-calculator.local
        path: /
