alertmanager:
  ingress:
    enabled: true
    ingressClassName: kong
    annotations:
      kubernetes.io/ingress.class: kong
    hosts:
      - host: alertmanager.loan-calculator.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - alertmanager.loan-calculator.local
        secretName: alertmanager.loan-calculator.local-tls