apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-calculator-backend
  namespace: loan-calculator
spec:
  selector:
    matchLabels:
      app: loan-calculator-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: loan-calculator-backend
    spec:
      containers:
      - name: loan-calculator-backend
        image: daszkiewiczk/loan-calculator:backend
        env:
          - name: DB_NAME
            value: db
          - name: DB_USER
            value: user
          - name: DB_PASSWORD
            value: password
          - name: DB_HOST
            value: postgres
        ports:
        - containerPort: 8080
        imagePullSecrets:
          - name: image-repository-secret

