apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-calculator-frontend
  namespace: loan-calculator
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 30s"
spec:
  selector:
    matchLabels:
      app: loan-calculator-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: loan-calculator-frontend
    spec:
      containers:
        - name: loan-calculator-frontend
          image: daszkiewiczk/loan-calculator:frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: image-repository-secret



