apiVersion: v1
kind: Secret
metadata:
  name: loan-calculator 
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:daszkiewiczk/credit-agricole 
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA7RKeD/o8Wn+kpK6JZ+AXVHghGiXXArE9a4ryDHBKofAAAAJBHFBXORxQV
    zgAAAAtzc2gtZWQyNTUxOQAAACA7RKeD/o8Wn+kpK6JZ+AXVHghGiXXArE9a4ryDHBKofA
    AAAEAsm5yyE3DZp7h9Z9S2QB5unYraV7SqV223ThGhNiwKCTtEp4P+jxaf6Skroln4BdUe
    CEaJdcCsT1rivIMcEqh8AAAABmFyZ29jZAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----

