apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: 'k8s/keel'
    repoURL: 'git@github.com:daszkiewiczk/credit-agricole'
    targetRevision: master
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - Replace=false

