name: build and push backend docker image

on:
  push:
    branches:
      - 'master'
    paths:
      - loan-calculator-app/loan-calculator-backend/**
      - .github/workflows/docker-build-push-backend.yml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'daszkiewiczk'
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: loan-calculator-app/loan-calculator-backend
          push: true
          # image tag specifies application instead of a version as a workaround -
          # - DockerHub free tier only permits one private repository per account
          tags: daszkiewiczk/loan-calculator:backend
